enum CalendarLanguageCode: String, CaseIterable, Identifiable {
    case BahasaIndonesia = "Bahasa Indonesia"
        case BahasaMalaysia = "Bahasa Malaysia"
        case Catala = "Català"
        case Dansk = "Dansk"
        case Deutsch = "Deutsch"
        case Eesti = "Eesti"
        case Espanol = "Español"
        case Filipino = "Filipino"
        case Francais = "Français"
        case Hindi = "Hindi"
        case Hrvatski = "Hrvatski"
        case Italiano = "Italiano"
        case Latviski = "Latviski"
        case Lietuviu = "Lietuvių"
        case Magyar = "Magyar"
        case Nederlands = "Nederlands"
        case Norsk = "Norsk"
        case Polski = "Polski"
        case Portugues = "Português"
        case PortuguesBrasileiro = "Português Brasileiro"
        case Romana = "Română"
        case Slovencina = "Slovenčina"
        case Srpski = "Srpski"
        case Suomi = "Suomi"
        case Svenska = "Svenska"
        case TiengViet = "Tiếng Việt"
        case Turkce = "Türkçe"
        case Islenska = "Íslenska"
        case Cestina = "Čeština"
        case Ellinika = "Ελληνικά"
        case Bulgarski = "Български"
        case Russkiy = "Русский"
        case Ukrainska = "Українська"
        case Ivrit = "עברית"
        case Arabic = "العربية"
        case Thai = "ภาษาไทย"
        case Japanese = "日本語"
        case SimplifiedChinese = "简体中文"
        case TraditionalChineseTaiwan = "繁體中文(台灣)"
        case TraditionalChineseHongKong = "繁體中文(香港)"
        case Korean = "한국어"
    
    var id: String { self.rawValue }
    var displayName: String { self.rawValue }
}
